# Generated by Django 3.1.4 on 2022-10-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_product_armodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ARModel',
            field=models.FileField(blank=True, null=True, upload_to='../frontend/public'),
        ),
    ]
