# Generated by Django 3.1.4 on 2022-10-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_product_armodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ARModel',
            field=models.FileField(blank=True, null=True, upload_to='public'),
        ),
    ]
